FROM golang:1.14

RUN mkdir /data
RUN mkdir /api
WORKDIR /api

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build cmd/main.go
# RUN cp /api/main /data/main

# WORKDIR /

# ENV IPFS_GATEWAY=${IPFS_GATEWAY}
# ENV IPFS_REV_PROXY_ADDR=${IPFS_REV_PROXY_ADDR}
# ENV LIVEPEER_COM_API_KEY=${LIVEPEER_COM_API_KEY}
# ENV LIVEPEER_PRICING_TOOL=${LIVEPEER_PRICING_TOOL}
# ENV PINATA_API_KEY=${PINATA_API_KEY}
# ENV PINATA_SECRET_KEY=${PINATA_SECRET_KEY}
# ENV POLL_INTERVAL=${POLL_INTERVAL}
ENV PORT=${PORT}
ENV DB_PATH=${DB_PATH}
ENV BROADCASTER_ENDPOINT=${BROADCASTER_ENDPOINT}
ENV LOG_FILE_PATH=${LOG_FILE_PATH}
ENV POLL_INTERVAL=${POLL_INTERVAL}

# ENV POW_TOKEN=${POW_TOKEN}
# ENV POWERGATE_ADDR=${POWERGATE_ADDR}
# ENV TRUSTED_MINERS=${TRUSTED_MINERS}
# ENV DEMUX_URL=${DEMUX_URL}
# ENV MONGO_URI=${MONGO_URI}

EXPOSE ${PORT}

CMD ["./main"]
