FROM golang:1.14

RUN mkdir /api
WORKDIR /api

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build cmd/main.go

ENV PORT=${PORT}
ENV DB_PATH=${DB_PATH}
ENV BROADCASTER_ENDPOINT=${BROADCASTER_ENDPOINT}
ENV LOG_FILE_PATH=${LOG_FILE_PATH}
ENV POLL_INTERVAL=${POLL_INTERVAL}

EXPOSE ${PORT}

CMD ["./main"]
